name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install go-bin-deb
        run: |
          go install github.com/groove-x/go-bin-deb@latest

      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build deb package
        run: |
          go mod download
          make deb
        env:
          VERSION: ${{ steps.get_version.outputs.version }}

      - name: Create Release
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Release ${{ github.ref_name }}" \
            prometheus-cgroup-exporter_${{ steps.get_version.outputs.version }}_amd64.deb \
            prometheus-cgroup-exporter_${{ steps.get_version.outputs.version }}_arm64.deb \
            --draft=false \
            --prerelease=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}